debug: true
http:
  host: 0.0.0.0
  port: 8080
mysql:
  host: wuhongyu.ltd
  port: 3306
  user: root
  password: 1056646612
  database: db2
redis:
  host: wuhongyu.ltd
  port: 6379
  db: 0
kafka:
  enable: false
  brokers:
    - localhost:9092