version: "3.9"  # optional since v1.27.0
services:
  c4best:
    build: .
    depends_on:
      - redis
      - mysql
      - zookeeper
      - kafka
    ports:
      - "8080:8080"
    volumes:
      - ./config.yaml:/root/config.yaml
    links:
      - redis
      - mysql
      - -zookeeper
      - kafka
  redis:
    image: redis
  mysql:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=123456
      - MYSQL_USER=root
      - MYSQL_PASSWORD=123456
  zookeeper:
    image: zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      - KAFKA_LISTENERS=PLAINTEXT://0.0.0.0:9092
